version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: govtjobsnow_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: govtjobsnow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-backup:/backup
    # PostgreSQL port only accessible internally 
    # Use different port if you need external access to avoid conflicts
    # ports:
    #   - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - govtjobs_network

  # Main Application
  app:
    build: .
    container_name: govtjobsnow_app
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/govtjobsnow
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: govtjobsnow
      # Add any other environment variables your app needs
      TZ: Asia/Kolkata
    # App port only accessible through Nginx
    # ports:
    #   - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    networks:
      - govtjobs_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/api/stats || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy (optional but recommended for production)
  nginx:
    image: nginx:alpine
    container_name: govtjobsnow_nginx
    restart: unless-stopped
    ports:
      - "8080:80"    # Use port 8080 to avoid conflicts with existing web server
      - "8443:443"   # Use port 8443 for HTTPS to avoid conflicts
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # For SSL certificates
    depends_on:
      - app
    networks:
      - govtjobs_network

volumes:
  postgres_data:
    driver: local

networks:
  govtjobs_network:
    driver: bridge
    # Use custom subnet to avoid conflicts with existing networks
    ipam:
      config:
        - subnet: 172.25.0.0/16